### ISSUE TITLE
[Question] Source

### ISSUE THREAD

**Issue by rea987** [nekonomicon/Poke646-android#1]
Hello,

That is not a bug. I wonder how did you port the game into *nix systems? Did you get the source code? Cause, when I asked about the Linux release on **ModDB**, I was told that reaching the source code would be impossible. Will you port more Half-Life mods; if yes, is **Sweet Half-Life** among them?

Thanks, regards.

**Comment by nekonomicon** [comment]
I just ported @malortie's steampipe-patches on other sdk.
I will port opensource mods and any open reimplementations.
@mittorn planned add special co-op mode to singleplayer mods.

>Sweet Half-Life

Seems @malortie planned to recreate Sweet HL source code. http://www.moddb.com/members/malortie/blogs/steampipe-patches-for-goldsource-modifications
Also, our teammate @LostGamerHL(lorbbbbb on ModDB) will be working on hl mods reimplementations too.

**Comment by rea987** [comment]
Sweet, thanks!
